In [1]:
import pandas as pd

In [2]:
df=pd.read_parquet(r'C:\Users\sgabalog\Documents\P3\Model\data_local\liverpool\processed\utility_scores_bulk.parquet')
df.head()

,household,sex,age_years,nssec8,pwkstat,salary_yearly,id,num_children,household_size,Postcode,...,8179,3113,6791,7615,6454,5276,7653,5454,8889,4873
0,0,MALE,74,NEVER,RETIRED,0.00,0,1,3,L33 4YT,...,0.0,0.0,0.001134,0.0,0.000248,0.0,0.0,0.000119,0.0,0.000895
1,1,MALE,86,NEVER,RETIRED,0.00,3,0,1,L33 1UW,...,0.0,0.0,0.001134,0.0,0.000248,0.0,0.0,0.000119,0.0,0.000895
2,2,FEMALE,71,SMALL,RETIRED,0.00,4,1,2,L33 4YU,...,0.0,0.0,0.001134,0.0,0.000248,0.0,0.0,0.000119,0.0,0.000895
3,3,FEMALE,74,LOWER,RETIRED,0.00,6,1,2,L33 1RZ,...,0.0,0.0,0.001134,0.0,0.000248,0.0,0.0,0.000119,0.0,0.000895
4,4,FEMALE,43,ROUTINE,EMPLOYEE_PT,9522.24,8,0,1,L33 9TY,...,0.0,0.0,0.002479,0.0,0.000544,0.0,0.0,0.000260,0.0,0.001956

In [1]:
from geopandas import read_parquet
import pandas as pd
df = pd.read_parquet(r"c:\Users\sgabalog\Documents\P3\Model\data_local\liverpool\inputs\Consumer_Agents\bulk_parameterised_consumer_agents_full.parquet")

In [2]:
# List of columns to keep
cols_to_keep = [
    'household', 
    'prob_walk', 
    'prob_pt', 
    'prob_drive'
]

# Create a new DataFrame with only these columns
df_filtered = df[cols_to_keep]

# To verify the change
print(df_filtered.head(50))

    household  prob_walk   prob_pt  prob_drive
0           0   0.136364  0.207508    0.656128
1           1   0.182631  0.554648    0.262721
2           2   0.130507  0.217048    0.652445
3           3   0.142286  0.215597    0.642117
4           4   0.067438  0.053756    0.878807
5           5   0.029792  0.047206    0.923002
6           6   0.043214  0.049322    0.907464
7           7   0.044478  0.062814    0.892708
8           8   0.127129  0.167844    0.705027
9           9   0.136290  0.535612    0.328098
10         10   0.066783  0.058178    0.875038
11         11   0.229085  0.235507    0.535407
12         12   0.256606  0.429863    0.313531
13         13   0.352191  0.132262    0.515547
14         14   0.195491  0.295211    0.509299
15         15   0.022908  0.024241    0.952851
16         16   0.026475  0.022740    0.950785
17         17   0.048219  0.036882    0.914898
18         18   0.253156  0.359689    0.387156
19         19   0.133992  0.290438    0.575570
20         20   0.013667  0.039681    0.946651
21         21   0.327107  0.242302    0.430591
22         22   0.131568  0.156318    0.712114
23         23   0.166724  0.365987    0.467289
24         24   0.250400  0.308144    0.441456
25         25   0.038770  0.030961    0.930269
26         26   0.027693  0.035814    0.936493
27         27   0.174761  0.549015    0.276224
28         28   0.156538  0.120939    0.722523
29         29   0.065881  0.090067    0.844052
30         30   0.204225  0.246342    0.549433
31         31   0.232073  0.315888    0.452039
32         32   0.384888  0.183409    0.431703
33         33   0.028907  0.035381    0.935713
34         34   0.072860  0.046735    0.880405
35         35   0.016450  0.015229    0.968321
36         36   0.118493  0.091687    0.789820
37         37   0.058018  0.065207    0.876775
38         38   0.041621  0.027965    0.930414
39         39   0.344791  0.179997    0.475212
40         40   0.213651  0.448627    0.337722
41         41   0.186921  0.447103    0.365976
42         42   0.134200  0.264220    0.601580
43         43   0.285539  0.195422    0.519039
44         44   0.283992  0.413972    0.302036
45         45   0.040592  0.061423    0.897985
46         46   0.051988  0.050220    0.897792
47         47   0.022294  0.014065    0.963641
48         48   0.289320  0.302115    0.408565
49         49   0.076553  0.082634    0.840814

In [9]:
df_filtered.head(20)

,household,stock_level,consumption_rate,shopping_threshold,prob_walk,prob_pt,prob_drive
0,0,108.000000,24.737143,27.345715,0.5,0.5,0.5
1,1,47.705882,14.028235,11.476471,0.5,0.5,0.5
2,2,61.454545,18.541819,15.089999,0.5,0.5,0.5
3,3,63.928571,18.550001,17.102142,0.5,0.5,0.5
4,4,90.375000,16.295626,22.431250,0.5,0.5,0.5
5,5,128.454545,21.746363,31.744545,0.5,0.5,0.5
6,6,87.937500,19.715000,20.371250,0.5,0.5,0.5
7,7,122.360000,19.816799,30.774799,0.5,0.5,0.5
8,8,91.875000,24.132500,22.776251,0.5,0.5,0.5
9,9,62.500000,18.285000,14.701667,0.5,0.5,0.5
10,10,113.727273,20.428181,30.814545,0.5,0.5,0.5
11,11,66.454545,14.469091,18.048182,0.5,0.5,0.5
12,12,50.285714,13.744286,13.795000,0.5,0.5,0.5
13,13,61.866667,13.824666,15.810667,0.5,0.5,0.5
14,14,74.125000,19.662500,16.491249,0.5,0.5,0.5
15,15,151.000000,41.367500,41.872501,0.5,0.5,0.5
16,16,173.166667,33.801666,45.345837,0.5,0.5,0.5
17,17,122.363636,23.595453,27.922728,0.5,0.5,0.5
18,18,38.533333,13.377334,8.542666,0.5,0.5,0.5
19,19,55.684211,18.302631,14.434737,0.5,0.5,0.5