In [1]:
import pandas as pd

In [2]:
df=pd.read_parquet(r'C:\Users\sgabalog\Documents\P3\Model\data_local\liverpool\processed\utility_scores_bulk.parquet')
df.head()

,household,sex,age_years,nssec8,pwkstat,salary_yearly,id,num_children,household_size,Postcode,...,8179,3113,6791,7615,6454,5276,7653,5454,8889,4873
0,0,MALE,74,NEVER,RETIRED,0.00,0,1,3,L33 4YT,...,0.0,0.0,0.001134,0.0,0.000248,0.0,0.0,0.000119,0.0,0.000895
1,1,MALE,86,NEVER,RETIRED,0.00,3,0,1,L33 1UW,...,0.0,0.0,0.001134,0.0,0.000248,0.0,0.0,0.000119,0.0,0.000895
2,2,FEMALE,71,SMALL,RETIRED,0.00,4,1,2,L33 4YU,...,0.0,0.0,0.001134,0.0,0.000248,0.0,0.0,0.000119,0.0,0.000895
3,3,FEMALE,74,LOWER,RETIRED,0.00,6,1,2,L33 1RZ,...,0.0,0.0,0.001134,0.0,0.000248,0.0,0.0,0.000119,0.0,0.000895
4,4,FEMALE,43,ROUTINE,EMPLOYEE_PT,9522.24,8,0,1,L33 9TY,...,0.0,0.0,0.002479,0.0,0.000544,0.0,0.0,0.000260,0.0,0.001956

In [7]:
print(list(df.columns))

['household', 'sex', 'age_years', 'nssec8', 'pwkstat', 'salary_yearly', 'id', 'num_children', 'household_size', 'Postcode', 'stock_level', 'consumption_rate', 'shopping_threshold', 'prob_convenience', 'prob_bulk', 'prob_online', 'amenity_type', 'channel_type', 'prob_walk', 'prob_drive', 'prob_pt', 'W_total', 'W_distance', 'W_personal_proffesional', 'W_cafe', 'W_retail', 'W_entertainment', 'W_restaurant', 'freq_comparison', 'prob_trip_comparison', 'freq_entertainment', 'prob_trip_entertainment', 'freq_service', 'prob_trip_service', 'freq_food_drink', 'prob_trip_food_drink', '7142', '669', '6445', '7605', '8816', '4205', '3376', '6119', '6120', '690', '2565', '8150', '8815', '5259', '8142', '4872', '2131', '1871', '8807', '5632', '920', '3533', '5857', '6116', '8141', '5053', '1104', '8145', '7375', '7601', '477', '2823', '3374', '6438', '4868', '2446', '4669', '3792', '8798', '7137', '8799', '1179', '8800', '8138', '7139', '6117', '2953', '4067', '3708', '1806', '4719', '3882', '8810', '7138', '6441', '4869', '3467', '5258', '8143', '9283', '224', '3534', '8519', '7604', '8144', '3710', '3302', '3375', '5629', '6439', '1164', '1355', '8802', '1974', '5256', '8801', '1453', '8803', '1268', '4322', '5858', '3711', '5441', '1752', '7614', '2348', '67', '4209', '4594', '8808', '1699', '2551', '8809', '2055', '950', '5052', '90', '5856', '5257', '8813', '5439', '1440', '3883', '6443', '574', '3469', '6444', '879', '3709', '5631', '3235', '979', '6766', '8820', '8804', '6966', '4066', '4145', '8817', '4973', '3970', '3535', '3057', '6446', '6440', '8805', '3004', '5051', '2230', '2911', '1664', '3968', '756', '819', '1281', '4592', '1565', '9300', '7606', '2707', '9477', '5440', '1245', '730', '4871', '1975', '2527', '7612', '4442', '1851', '9455', '8148', '6771', '8151', '8819', '6770', '2222', '8152', '7144', '6772', '6769', '4207', '4323', '2954', '6768', '2686', '4206', '3969', '5054', '9576', '2550', '1423', '3505', '6118', '7611', '6114', '8806', '8812', '1766', '2056', '6115', '7607', '3618', '3468', '7163', '4877', '1222', '4204', '8851', '7140', '8177', '4720', '7609', '4870', '5630', '5866', '7141', '1000', '8147', '2447', '7608', '6442', '4068', '6767', '6022', '7143', '1388', '4443', '1728', '8852', '9356', '1010', '4325', '461', '7165', '7164', '8176', '8849', '5640', '2567', '7162', '5865', '2568', '5061', '3339', '301', '7634', '1356', '3798', '4074', '8179', '3113', '6791', '7615', '6454', '5276', '7653', '5454', '8889', '4873']

In [8]:
# List of columns to keep
cols_to_keep = [
    'household', 
    'stock_level', 
    'consumption_rate', 
    'shopping_threshold', 
    'prob_walk', 
    'prob_pt', 
    'prob_drive'
]

# Create a new DataFrame with only these columns
df_filtered = df[cols_to_keep]

# To verify the change
print(df_filtered.head())

   household  stock_level  consumption_rate  shopping_threshold  prob_walk  \
0          0   108.000000         24.737143           27.345715        0.5
1          1    47.705882         14.028235           11.476471        0.5
2          2    61.454545         18.541819           15.089999        0.5
3          3    63.928571         18.550001           17.102142        0.5
4          4    90.375000         16.295626           22.431250        0.5

   prob_pt  prob_drive
0      0.5         0.5
1      0.5         0.5
2      0.5         0.5
3      0.5         0.5
4      0.5         0.5

In [9]:
df_filtered.head(20)

,household,stock_level,consumption_rate,shopping_threshold,prob_walk,prob_pt,prob_drive
0,0,108.000000,24.737143,27.345715,0.5,0.5,0.5
1,1,47.705882,14.028235,11.476471,0.5,0.5,0.5
2,2,61.454545,18.541819,15.089999,0.5,0.5,0.5
3,3,63.928571,18.550001,17.102142,0.5,0.5,0.5
4,4,90.375000,16.295626,22.431250,0.5,0.5,0.5
5,5,128.454545,21.746363,31.744545,0.5,0.5,0.5
6,6,87.937500,19.715000,20.371250,0.5,0.5,0.5
7,7,122.360000,19.816799,30.774799,0.5,0.5,0.5
8,8,91.875000,24.132500,22.776251,0.5,0.5,0.5
9,9,62.500000,18.285000,14.701667,0.5,0.5,0.5
10,10,113.727273,20.428181,30.814545,0.5,0.5,0.5
11,11,66.454545,14.469091,18.048182,0.5,0.5,0.5
12,12,50.285714,13.744286,13.795000,0.5,0.5,0.5
13,13,61.866667,13.824666,15.810667,0.5,0.5,0.5
14,14,74.125000,19.662500,16.491249,0.5,0.5,0.5
15,15,151.000000,41.367500,41.872501,0.5,0.5,0.5
16,16,173.166667,33.801666,45.345837,0.5,0.5,0.5
17,17,122.363636,23.595453,27.922728,0.5,0.5,0.5
18,18,38.533333,13.377334,8.542666,0.5,0.5,0.5
19,19,55.684211,18.302631,14.434737,0.5,0.5,0.5